//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.18 at 06:59:08 PM MSK 
//


package by.victor.greenhouse.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Multiplying-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Multiplying-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="leaf"/>
 *     &lt;enumeration value="stalk"/>
 *     &lt;enumeration value="seed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Multiplying-type")
@XmlEnum
public enum MultiplyingType {

    @XmlEnumValue("leaf")
    LEAF("leaf"),
    @XmlEnumValue("stalk")
    STALK("stalk"),
    @XmlEnumValue("seed")
    SEED("seed");
    private final String value;

    MultiplyingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MultiplyingType fromValue(String v) {
        for (MultiplyingType c: MultiplyingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
