//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.18 at 06:59:08 PM MSK 
//


package by.victor.greenhouse.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the entyty package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Plant_QNAME = new QName("http://by.victor.epam", "plant");
    private final static QName _Flower_QNAME = new QName("http://by.victor.epam", "flower");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: entyty
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Flower }
     * 
     */
    public Flower createFlower() {
        return new Flower();
    }

    /**
     * Create an instance of {@link Flowers }
     * 
     */
    public Flowers createFlowers() {
        return new Flowers();
    }

    /**
     * Create an instance of {@link Plant }
     * 
     */
    public Plant createPlant() {
        return new Plant();
    }

    /**
     * Create an instance of {@link VisualParameters }
     * 
     */
    public VisualParameters createVisualParameters() {
        return new VisualParameters();
    }

    /**
     * Create an instance of {@link GrowingTips }
     * 
     */
    public GrowingTips createGrowingTips() {
        return new GrowingTips();
    }

    /**
     * Create an instance of {@link Flower.FloweringTime }
     * 
     */
    public Flower.FloweringTime createFlowerFloweringTime() {
        return new Flower.FloweringTime();
    }

    /**
     * Create an instance of {@link Flower.PossibleInflorescenceColor }
     * 
     */
    public Flower.PossibleInflorescenceColor createFlowerPossibleInflorescenceColor() {
        return new Flower.PossibleInflorescenceColor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Plant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://by.victor.epam", name = "plant")
    public JAXBElement<Plant> createPlant(Plant value) {
        return new JAXBElement<Plant>(_Plant_QNAME, Plant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flower }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://by.victor.epam", name = "flower", substitutionHeadNamespace = "http://by.victor.epam", substitutionHeadName = "plant")
    public JAXBElement<Flower> createFlower(Flower value) {
        return new JAXBElement<Flower>(_Flower_QNAME, Flower.class, null, value);
    }

}
